# Generated by Django 4.0.6 on 2022-09-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
