# Generated by Django 4.0.6 on 2022-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_orderitem_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
